jdk:
  - openjdk11

language: java

services:
  - mongodb

before_script:
  - chmod +x gradlew
before_install:
  - chmod +x gradlew

script: 
  - ./gradlew test

branches:
  only:
    - main

deploy:
  - provider: heroku
    api_key: 22c5b519-a454-4299-8cab-4cdb244b1283
    app: dev-moviescombine-api
    on:
      branch: main